net: deepset # deepset or particlenet

epochs: 100
shuffle_buffer: 100

loss: mean_absolute_error
optimizer: adam
lr: 1.e-3

callbacks:
  reduce_lr_on_plateau:
    factor: 0.5
    min_lr: 1.e-8
    min_delta: 1.e-4
    patience: 5
  early_stopping:
    min_delta: 1.e-4
    patience: 7

model:
  deepset:
    type: mlp # mlp or resnet
    activation: relu
    initializer: he_normal
    batch_norm: False
    dropout: 0
    units: [100, 100, 100, 100]

  particlenet:
    activation: relu
    initializer: he_normal
    batch_norm: False
    shortcut: True
    pooling: average # average or max
    num_points: 100
    K: 16
    channels: [
      [64, 64, 64],
      [128, 128, 128],
      [256, 256, 256],
      [512, 512, 512]
    ]
    dropout: 0
    units: [512, 256, 128, 64]

data:
  batch_size: 512
  train_size: 0.6
  validation_size: 0.2
  test_size: 0.2

  num_points: 64 # ParticleNet point cutoff
  
  features:
    jet: 
      numerical: [
        pt, eta, phi, mass, area, rho, num_pv
      ]
      categorical: []
    ch:
      numerical: [
        ch_pt, ch_eta, ch_phi, ch_dxy, ch_dxy_significance, ch_dz,
        ch_num_hits, ch_num_pixel_hits, ch_lost_hits, ch_norm_chi2
      ]
      categorical: [ch_id, ch_pv_ass]
    ne:
      numerical: [
        ne_pt, ne_eta, ne_phi, ne_hcal_frac
      ]
      categorical: [ne_id]
    sv:
      numerical: [
        sv_mass, sv_pt, sv_distance, sv_significance
      ]
      categorical: [sv_num_tracks]
